version: "3.8"
services:
  loadbalancer:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    build: ./backend
    environment:
      - SERVER_ID=backend-1
    ports:
      - "5001:5001"

  backend2:
    build: ./backend
    environment:
      - SERVER_ID=backend-2
    ports:
      - "5002:5001"

  backend3:
    build: ./backend
    environment:
      - SERVER_ID=backend-3
    ports:
      - "5003:5001"
